apiVersion: v1
kind: BuildConfig
metadata:
  name: nysteveapp-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent { label "maven" }
          stages {
            stage("Clone Source") {
              steps {
                checkout([$class: 'GitSCM',
                            branches: [[name: '*/master']],
                            extensions: [
                              [$class: 'RelativeTargetDirectory', relativeTargetDir: 'nysteveapp']
                            ],
                            userRemoteConfigs: [[url: 'https://bitbucket.org/stevshil/hello-world-spring-boot.git']]
                        ])
              }
            }
            stage("Build JAR") {
              steps {
                dir('nysteveapp') {
                  sh 'mvn clean package'
                }
              }
            }
            stage("Create Build") {
              steps {
                dir('nysteveapp') {
                  sh 'oc new-build --strategy docker --binary --name nystevebin'
                }
              }
            }
            stage("Build Image") {
              steps {
                dir('nysteveapp') {
                  sh 'oc start-build nystevebin --from-dir . --follow'
                }
              }
            }
          }
        }
    type: JenkinsPipeline
  triggers: []
